2024-03-12 16:21:45.762 database_manager:772 [INFO] [MainThread 139637858173568] Starting dbm in dbm starter
2024-03-12 16:21:45.762 database_manager:607 [INFO] [Monitoring-migrate-priority 139637070739200] Starting processing for queue priority
2024-03-12 16:21:45.763 database_manager:607 [INFO] [Monitoring-migrate-node 139637079131904] Starting processing for queue node
2024-03-12 16:21:45.764 database_manager:607 [INFO] [Monitoring-migrate-block 139637087524608] Starting processing for queue block
2024-03-12 16:21:45.764 database_manager:607 [INFO] [Monitoring-migrate-resource 139637095917312] Starting processing for queue resource
2024-03-12 16:21:45.765 database_manager:607 [INFO] [Monitoring-migrate-energy 139637104310016] Starting processing for queue energy
2024-03-12 16:21:46.266 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:46.768 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:46.783 database_manager:657 [INFO] [Monitoring-migrate-block 139637087524608] Will put [{'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c', 'status': 'PENDING', 'timestamp': datetime.datetime(2024, 3, 12, 16, 21, 46, 781502), 'executor_label': 'htex_Local', 'job_id': '420034', 'block_id': '0'}] to pending block queue
2024-03-12 16:21:47.275 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:47.776 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:48.278 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:48.400 database_manager:651 [INFO] [Monitoring-migrate-node 139637079131904] Will put {'last_heartbeat': datetime.datetime(2024, 3, 12, 16, 21, 48, 376826), 'idle_since': 1710260508.3768265, 'block_id': '0', 'max_capacity': 48, 'worker_count': 48, 'active': True, 'tasks': [], 'parsl_v': '1.3.0-dev', 'python_v': '3.10.13', 'uid': '1eaab58ec9ad', 'prefetch_capacity': 0, 'os': 'Linux', 'hostname': 'resilient-compute', 'dir': '/home/cc/resilient_compute/performance_experiments', 'cpu_count': 24, 'total_memory': 201297137664, 'timestamp': datetime.datetime(2024, 3, 12, 16, 21, 48, 377159), 'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c'} to pending node queue
2024-03-12 16:21:48.784 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:49.285 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: []
2024-03-12 16:21:49.786 database_manager:543 [ERROR] [MainThread 139637858173568] Resource messages: [{'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c', 'try_id': 0, 'task_id': 0, 'hostname': 'resilient-compute', 'block_id': '0', 'first_msg': True, 'last_msg': False, 'timestamp': datetime.datetime(2024, 3, 12, 16, 21, 49, 474143), 'pid': 420088}]
2024-03-12 16:21:49.791 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:50.793 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:51.796 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:51.809 database_manager:657 [INFO] [Monitoring-migrate-block 139637087524608] Will put [{'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c', 'status': 'RUNNING', 'timestamp': datetime.datetime(2024, 3, 12, 16, 21, 51, 808790), 'executor_label': 'htex_Local', 'job_id': '420034', 'block_id': '0'}] to pending block queue
2024-03-12 16:21:52.798 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:53.801 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:54.804 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:55.807 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:56.809 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:57.812 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:58.813 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:21:59.816 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:00.819 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:01.822 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:02.825 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:03.827 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:04.830 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:05.833 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:06.836 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:07.839 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:08.841 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:09.844 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:10.847 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:11.849 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:12.852 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:13.855 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:14.857 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:15.860 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:16.863 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:17.865 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:18.868 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:19.871 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:20.874 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:21.877 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:22.879 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:23.882 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:24.885 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:25.887 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:26.890 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:27.893 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:28.896 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:29.898 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:30.901 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:31.903 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:32.906 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:33.909 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:34.911 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:35.915 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:36.917 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:37.920 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:38.922 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:39.925 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:40.928 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:41.930 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:42.933 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:43.936 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:44.939 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:45.942 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:46.944 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:47.947 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:48.950 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:49.952 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:50.955 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:51.958 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:52.961 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:53.963 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:54.966 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:55.969 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:56.971 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:57.974 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:58.977 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:22:59.982 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:00.984 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:01.987 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:02.990 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:03.992 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:04.995 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:05.998 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:07.000 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:08.003 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:09.006 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:10.008 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:11.011 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:12.014 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:13.017 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:14.019 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:15.022 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:16.024 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:17.028 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:18.030 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:19.033 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:20.036 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:21.038 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:22.041 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:23.044 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:24.046 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:25.049 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:25.897 database_manager:651 [INFO] [Monitoring-migrate-node 139637079131904] Will put {'last_heartbeat': datetime.datetime(2024, 3, 12, 16, 23, 24, 761437), 'idle_since': 1710260605.8715005, 'block_id': '0', 'max_capacity': 48, 'worker_count': 48, 'active': False, 'tasks': [], 'parsl_v': '1.3.0-dev', 'python_v': '3.10.13', 'uid': '1eaab58ec9ad', 'prefetch_capacity': 0, 'os': 'Linux', 'hostname': 'resilient-compute', 'dir': '/home/cc/resilient_compute/performance_experiments', 'cpu_count': 24, 'total_memory': 201297137664, 'timestamp': datetime.datetime(2024, 3, 12, 16, 23, 25, 886263), 'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c'} to pending node queue
2024-03-12 16:23:25.968 database_manager:657 [INFO] [Monitoring-migrate-block 139637087524608] Will put [{'run_id': '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c', 'status': 'CANCELLED', 'timestamp': datetime.datetime(2024, 3, 12, 16, 23, 25, 939424), 'executor_label': 'htex_Local', 'job_id': '420034', 'block_id': '0'}] to pending block queue
2024-03-12 16:23:26.052 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:27.055 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:28.057 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:28.995 database_manager:735 [INFO] [Monitoring-migrate-priority 139637070739200] Database Manager cleanup initiated.
2024-03-12 16:23:28.995 database_manager:737 [INFO] [Monitoring-migrate-priority 139637070739200] Logging workflow end info to database due to abnormal exit
2024-03-12 16:23:29.059 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:30.062 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:31.064 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:32.067 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:33.070 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:34.072 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:35.074 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:36.077 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:37.080 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:38.082 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:39.085 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:40.088 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:41.090 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:42.093 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:43.095 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:44.098 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:45.100 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:46.104 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:47.106 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:48.109 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:49.111 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:50.114 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:51.117 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:52.119 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:53.122 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:54.124 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:55.128 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:56.130 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:57.133 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:58.135 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:23:59.137 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:00.140 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:01.143 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:02.145 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:03.148 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:04.151 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:05.154 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:06.156 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:07.159 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:08.161 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:09.164 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:10.166 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:11.169 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:12.172 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:13.175 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:14.177 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:15.180 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:16.182 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:17.185 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:18.187 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:19.190 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:20.193 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:21.195 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:22.198 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:23.201 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:24.203 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:25.206 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:26.208 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:27.211 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:28.213 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:29.216 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:30.218 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:31.222 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:32.224 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:33.227 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:34.229 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:35.232 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:36.234 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:37.237 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:38.239 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:39.242 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:40.245 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:41.247 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:42.250 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:43.252 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:44.255 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:45.257 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:46.260 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:47.263 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:48.265 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:49.269 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:50.272 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:51.274 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:52.277 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:53.279 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:54.282 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:55.284 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:56.287 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:57.289 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:58.293 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:24:59.295 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:00.298 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:01.300 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:02.303 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:03.305 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:04.308 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:05.310 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:06.313 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:07.316 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:08.318 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:09.321 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:10.324 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:11.326 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:12.329 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:13.331 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:14.333 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:15.335 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:16.338 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:17.341 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:18.343 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:19.346 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:20.348 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:21.351 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:22.353 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:23.356 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:24.358 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:25.361 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:26.363 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:27.366 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:28.368 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:29.371 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:30.373 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:31.376 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:32.378 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:33.381 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:34.384 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:35.386 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:36.389 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:37.391 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:38.394 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:39.396 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:40.398 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:41.401 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:42.403 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:43.406 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:44.409 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:45.411 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:46.414 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:47.416 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:48.419 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:49.421 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:50.423 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:51.426 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:52.429 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:53.431 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:54.434 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:55.436 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:56.439 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:57.441 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:58.444 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:25:59.446 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:00.449 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:01.452 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:02.454 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:03.457 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:04.459 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:05.461 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:06.463 database_manager:674 [WARNING] [MainThread 139637858173568] Got a database OperationalError. Ignoring and retrying on the assumption that it is recoverable: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-12 16:26:07.413 database_manager:679 [ERROR] [MainThread 139637858173568] KeyboardInterrupt when trying to update Table try
Traceback (most recent call last):
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: pid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 667, in _update
    logger.exception("KeyboardInterrupt when trying to update Table {}".format(table))
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 93, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4660, in bulk_update_mappings
    self._bulk_save_mappings(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4699, in _bulk_save_mappings
    with util.safe_reraise():
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4680, in _bulk_save_mappings
    bulk_persistence._bulk_update(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 328, in _bulk_update
    persistence._emit_update_statements(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 676, in _update
    self.db.rollback()
KeyboardInterrupt
2024-03-12 16:26:07.420 database_manager:775 [ERROR] [MainThread 139637858173568] KeyboardInterrupt signal caught
Traceback (most recent call last):
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: pid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 667, in _update
    logger.exception("KeyboardInterrupt when trying to update Table {}".format(table))
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 93, in update
    self.session.bulk_update_mappings(mapper, mappings)
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4660, in bulk_update_mappings
    self._bulk_save_mappings(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4699, in _bulk_save_mappings
    with util.safe_reraise():
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4680, in _bulk_save_mappings
    bulk_persistence._bulk_update(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 328, in _bulk_update
    persistence._emit_update_statements(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 513, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1630, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/home/cc/miniconda3/envs/new_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: pid
[SQL: UPDATE try SET block_id=?, hostname=?, pid=?, task_try_time_running=? WHERE try.try_id = ? AND try.task_id = ? AND try.run_id = ?]
[parameters: ('0', 'resilient-compute', 420088, '2024-03-12 16:21:49.474143', 0, 0, '16d5d04a-4521-4d38-8a6d-f33e5fbe3d7c')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 773, in dbm_starter
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 581, in start
    else:
  File "/home/cc/parsl_resilient/parsl/monitoring/db_manager.py", line 676, in _update
    self.db.rollback()
KeyboardInterrupt
2024-03-12 16:26:07.420 database_manager:735 [INFO] [MainThread 139637858173568] Database Manager cleanup initiated.
2024-03-12 16:26:07.420 database_manager:737 [INFO] [MainThread 139637858173568] Logging workflow end info to database due to abnormal exit
